### PR TITLE
Config validating of pdd

### LINKED ISSUE #2: Add pdd

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #2

### CODE REVIEW

**Comment by levBagryansky** [comment]
@c71n93 @mmamayka please check

**Comment by levBagryansky** [comment]
@mmamayka @mmamayka please check

**Review by c71n93 — DISMISSED** [review]
@levBagryansky Nice

**Review by mmamayka — CHANGES_REQUESTED** [review]
Our main branch called "main", so there is no master branch. Please remove its references. Also I would propose to use 'ubuntu-latest' as OS of CI test just to avoid mismatch of versions in CI tests

**Comment by levBagryansky** [comment]
@mmamayka Indeed, we already chose main. Why do we need the same version of ubunu in pdd test and in other checks? Pdd does not run the code of the project but check correctness of `todo`. Maybe its better to start it on any os where it can work

**Comment by mmamayka** [comment]
> @mmamayka Indeed, we already chose main. Why do we need the same version of ubunu in pdd test and in other checks? Pdd does not run the code of the project but check correctness of `todo`. Maybe its better to start it on any os where it can work

Just for unification. Probably, once, one of us  will try to add other CI test copy-pasting this one....

**Pull request merged**
